name: infra

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: terraform

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~1.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~1.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -var="cert_arn=${{ vars.CERT_ARN }}"

  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: plan
    environment: apply
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~1.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve -var="cert_arn=${{ vars.CERT_ARN }}"
